# channel
TERMINAL = "terminal"
WECHAT = "wechat"
WECHAT_MP = "wechat_mp"
WECHAT_MP_SERVICE = "wechat_mp_service"
WECHAT_COM = "wechat_com"
QQ = "qq"
GMAIL = "gmail"
TELEGRAM = "telegram"
SLACK = "slack"
HTTP = "http"
DINGTALK = "dingtalk"
FEISHU = "feishu"
DISCORD = "discord"

# model
OPEN_AI = "openai"
CHATGPT = "chatgpt"
BAIDU = "baidu"
BING = "bing"
BARD = "bard"